"""create core tables"""
from alembic import op
import sqlalchemy as sa

revision = '18eee7375e31'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_flagged', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_address', sa.String(length=300), nullable=False),
    sa.Column('street_address', sa.String(length=200), nullable=True),
    sa.Column('suburb', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=4), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=24), nullable=False),
    sa.Column('land_area_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('building_area_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('tenant_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sector IN ('SERVICE_STATION','QSR','HEALTHCARE','OTHER')", name='property_sector'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_canonical_address'), 'properties', ['canonical_address'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_region'), 'properties', ['region'], unique=False)
    op.create_index(op.f('ix_properties_sector'), 'properties', ['sector'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('raw_address', sa.Text(), nullable=True),
    sa.Column('raw_owner', sa.Text(), nullable=True),
    sa.Column('raw_tenant', sa.Text(), nullable=True),
    sa.Column('raw_sale_price', sa.Text(), nullable=True),
    sa.Column('raw_sale_date', sa.Text(), nullable=True),
    sa.Column('raw_land_area', sa.Text(), nullable=True),
    sa.Column('raw_building_area', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('candidate_property_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_observations_import_job_id'), 'raw_observations', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_raw_observations_status'), 'raw_observations', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('reported_yield', sa.Numeric(precision=7, scale=5), nullable=True),
    sa.Column('land_area_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('building_area_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_property_date', 'transactions', ['property_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_property_id'), 'transactions', ['property_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_property_id'), table_name='transactions')
    op.drop_index('ix_transaction_property_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_raw_observations_status'), table_name='raw_observations')
    op.drop_index(op.f('ix_raw_observations_import_job_id'), table_name='raw_observations')
    op.drop_table('raw_observations')
    op.drop_table('sources')
    op.drop_index(op.f('ix_properties_sector'), table_name='properties')
    op.drop_index(op.f('ix_properties_region'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_canonical_address'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
